SUPABASE_URL = "https://jdntvqnawbyhfcpoakyj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbnR2cW5hd2J5aGZjcG9ha3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyOTYyOTksImV4cCI6MjA5Mjg3MjI5OX0.ofADYIiWxiUCpTns7_hha_EyQSsGLbEba38BqyPNduw"
